---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kymzky.github.io/helm-homelab'
    chart: adguard-home
    targetRevision: 1.0.2
    helm:
      values: |
        services:
          dns:
            type: LoadBalancer
        ingresses:
          http:
            enabled: true
            className: traefik
            hosts:
              - host: adguard.{{ .Values.config.domain }}
                paths:
                  - path: /
                    pathType: Prefix
        bootstrapConfig:
          dns:
            rewrites:
              - domain: 'openmediavault.{{ .Values.config.domain }}'
                answer: {{ .Values.apps.nfsProvisioner.server }}
              - domain: '*.{{ .Values.config.domain }}'
                answer: {{ .Values.cluster.ip }}
  destination:
    server: {{ .Values.cluster.server }}
    namespace: adguard
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
