{{- if hasKey .Values "ddnsUpdater" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns-updater-secret
  namespace: ddns-updater
spec:
  encryptedData:
    config: {{ .Values.apps.ddnsUpdater.encryptedConfig }}
  template:
    metadata:
      creationTimestamp: null
      name: ddns-updater-secret
      namespace: ddns-updater
    type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ddns-updater
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kymzky.github.io/helm-homelab'
    chart: ddns-updater
    targetRevision: 1.0.0
    helm:
      values: |
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: ddnsupdater.{{ .Values.config.domain }}
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: {{ .Values.cluster.server }}
    namespace: ddns-updater
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
