---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kymzky.github.io/helm-homelab'
    chart: jellyseerr
    targetRevision: 1.0.1
    helm:
      values: |
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: jellyseerr.{{ .Values.config.domain }}
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          storageClass: longhorn
  destination:
    server: {{ .Values.cluster.server }}
    namespace: media-stack
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
