---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-stack-storage
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: {{ .Values.config.mediaStackStorageSize }}
