---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-services-storage
  namespace: media-services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: {{ .Values.config.mediaServicesStorageSize }}
