---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://nextcloud.github.io/helm'
    chart: nextcloud
    targetRevision: 6.6.9
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: longhorn
          nextcloudData:
            enabled: true
            subPath: nextcloud
            existingClaim: media-services-storage
        ingress:
          enabled: true
          className: traefik
        phpClientHttpsFix:
          enabled: true
        nextcloud:
          host: nextcloud.{{ .Values.config.domain }}
          phpConfigs:
            zz-filesize.ini: |-
              upload_max_filesize: 15G
              post_max_size: 15G
  destination:
    server: {{ .Values.cluster.server }}
    namespace: media-services
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
