---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    password: {{ .Values.apps.nextcloud.encryptedPassword }}
    postgres-password: {{ .Values.apps.nextcloud.postgresEncryptedPassword }}
    postgres-username: {{ .Values.apps.nextcloud.postgresEncryptedUsername }}
    username: {{ .Values.apps.nextcloud.encryptedUsername }}
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud
    type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://nextcloud.github.io/helm'
    chart: nextcloud
    targetRevision: 6.6.5
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: longhorn
          size: {{ .Values.apps.nextcloud.diskSize }}
        ingress:
          enabled: true
          className: traefik
        nextcloud:
          host: nextcloud.{{ .Values.config.domain }}
          existingSecret:
            enabled: true
            secretName: nextcloud-secret
            usernameKey: username
            passwordKey: password
          extraVolumes:
            - name: nfs
              nfs:
                server: "{{ .Values.apps.nfsProvisioner.server }}"
                path: "{{ .Values.apps.nfsProvisioner.path }}"
                readOnly: false
          extraVolumeMounts:
            - name: nfs
              mountPath: "/nfs"
        externalDatabase:
          enabled: true
          type: postgresql
          existingSecret:
            enabled: true
            secretName: nextcloud-secret
            usernameKey: postgres-username
            passwordKey: postgres-password
        postgresql:
          enabled: true
          global:
            postgresql:
              auth:
                existingSecret: nextcloud-secret
                secretKeys:
                  userPasswordKey: postgres-password
          primary:
            persistence:
              enabled: true
              storageClass: longhorn
  destination:
    server: {{ .Values.cluster.server }}
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
