---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: media-services
spec:
  encryptedData:
    password: {{ .Values.apps.nextcloud.encryptedPassword }}
    postgres-password: {{ .Values.apps.nextcloud.postgresEncryptedPassword }}
    postgres-username: {{ .Values.apps.nextcloud.postgresEncryptedUsername }}
    username: {{ .Values.apps.nextcloud.encryptedUsername }}
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: media-services
    type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://nextcloud.github.io/helm'
    chart: nextcloud
    targetRevision: 6.5.2
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: longhorn
          nextcloudData:
            enabled: true
            subPath: nextcloud
            existingClaim: media-services-storage
        ingress:
          enabled: true
          className: traefik
        phpClientHttpsFix:
          enabled: true
        nextcloud:
          host: nextcloud.{{ .Values.config.domain }}
          existingSecret:
            enabled: true
            secretName: nextcloud-secret
            usernameKey: username
            passwordKey: password
          phpConfigs:
            zz-filesize.ini: |-
              upload_max_filesize: 15G
              post_max_size: 15G
          configs:
            logging.config.php: |-
              <?php
              $CONFIG = array (
                'loglevel' => 0,
                );
  destination:
    server: {{ .Values.cluster.server }}
    namespace: media-services
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
