---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-secret
  namespace: monitoring
spec:
  encryptedData:
    api-key: {{ .Values.apps.telegrammy.encryptedOpenAiApiKey }}
  template:
    metadata:
      creationTimestamp: null
      name: openai-secret
      namespace: monitoring
    type: Opaque
