---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 27.4.0
    helm:
      values: |
        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - prometheus.{{ .Values.domain }}
          persistentVolume:
            storageClass: longhorn
  destination:
    server: {{ .Values.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
