---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kymzky.github.io/helm-homelab'
    chart: prowlarr
    targetRevision: 1.0.0
    helm:
      values: |
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: prowlarr.{{ .Values.domain }}
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          storageClass: longhorn
  destination:
    server: {{ .Values.server }}
    namespace: media-stack
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
