---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kymzky.github.io/helm-homelab'
    chart: sabnzbd
    targetRevision: 1.0.0
    helm:
      values: |
        ingress:
          main:
            enabled: true
            ingressClassName: traefik
            hosts:
              - host: sabnzbd.{{ .Values.domain }}
                paths:
                  - path: /
                    pathType: Prefix
        persistence:
          config:
            enabled: true
            storageClass: longhorn
          downloads:
            enabled: true
            existingClaim: media-stack-storage
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - sed -i -e "s/^host_whitelist *=.*$/host_whitelist = sabnzbd.{{ .Values.domain }}/g" /config/sabnzbd.ini
  destination:
    server: {{ .Values.server }}
    namespace: media-stack
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
