---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    chart: sealed-secrets
    targetRevision: 2.17.1
    helm:
      values: |
        fullnameOverride: "sealed-secrets-controller"
  destination:
    server: {{ .Values.server }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
