---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    ansible-vault-pass: {{ .Values.apps.telegrammy.encryptedAnsibleVaultPass }}
    ssh-private-key: {{ .Values.apps.telegrammy.encryptedSshPrivateKey }}
    telegram-id: {{ .Values.config.encryptedTelegramId }}
    telegram-token: {{ .Values.config.encryptedTelegramToken }}
  template:
    metadata:
      creationTimestamp: null
      name: telegram-secret
      namespace: monitoring
    type: Opaque
