---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    telegram-id: {{ .Values.encryptedTelegramId }}
    telegram-token: {{ .Values.encryptedTelegramToken }}
  template:
    metadata:
      creationTimestamp: null
      name: telegram-secret
      namespace: monitoring
    type: Opaque
