---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegrammy-config
  namespace: monitoring
data:
  config.yaml: |
    ---
    shellPath: "/bin/bash"
    pollInterval: 5

    responseJobs:

      - trigger: "configuration"
        command: "cat /etc/telegrammy/config.yaml"
        message: "```\n%s```"
        parseMode: MarkdownV2
        escapeCharacters:
          - "`"

      - trigger: "reset"
        command: "rm -f /etc/telegrammy/conversation"
        message: "ChatGPT conversation reset"

    cronJobs:

      - schedule: "20 16 * * *"
        message: "Alive"
        parseMode: HTML
