---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-secret
  namespace: monitoring
spec:
  encryptedData:
    api-key: {{ .Values.apps.telegrammy.encryptedOpenAiApiKey }}
  template:
    metadata:
      creationTimestamp: null
      name: openai-secret
      namespace: monitoring
    type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegrammy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kymzky.github.io/helm-homelab'
    chart: telegrammy
    targetRevision: 1.3.2
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: longhorn
  destination:
    server: {{ .Values.cluster.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
