---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegrammy-config
  namespace: monitoring
data:
  config.yaml: |
    ---
    shellPath: "/bin/bash"
    pollInterval: 5

    initCommand: |
      apk add openssh git ansible
      mkdir ~/.ssh
      echo $SSH_PRIVATE_KEY > ~/.ssh/id_ed25519
      chmod 400 ~/.ssh/id_ed25519
      echo $ANSIBLE_VAULT_PASS > ~/.vault-pass

    responseJobs:

      - trigger: "configuration"
        command: "cat /etc/telegrammy/config.yaml"
        message: "```\n%s```"
        parseMode: MarkdownV2
        escapeCharacters:
          - "`"

      - trigger: "reset"
        command: "rm -f /etc/telegrammy/conversation"
        message: "ChatGPT conversation reset"

      - trigger: "Update"
        command: |
          git clone --quiet https://github.com/kymzky/ansible-homelab.git
          cd ansible-homelab
          echo "[defaults]
          host_key_checking = False" > ansible.cfg
          git pull --quiet
          ansible-playbook -i inventory/prod.yaml playbooks/update.yaml > /tmp/ansible.log
          cat /tmp/ansible.log
        message: "Update:\n```\n%s```"
        parseMode: MarkdownV2
        escapeCharacters:
          - "`"

      - trigger: "Backup"
        command: |
          git clone --quiet https://github.com/kymzky/ansible-homelab.git
          cd ansible-homelab
          echo "[defaults]
          host_key_checking = False" > ansible.cfg
          git pull --quiet
          ansible-playbook --vault-pass-file ~/.vault-pass -i inventory/prod.yaml playbooks/backup.yaml > /tmp/ansible.log
          cat /tmp/ansible.log
        message: "Backup:\n```\n%s```"
        parseMode: MarkdownV2
        escapeCharacters:
          - "`"

    cronJobs:

      - schedule: "20 16 * * *"
        message: "{{ .Values.apps.telegrammy.grafanaDashboardUrl }}"
        parseMode: HTML
