---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wg-easy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kymzky.github.io/helm-homelab'
    chart: wg-easy
    targetRevision: 1.1.0
    helm:
      values: |
        env:
          WG_HOST: wireguard.{{ .Values.config.domain }}
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: wireguard.{{ .Values.config.domain }}
              paths:
                - path: /
                  pathType: Prefix
        volume:
          className: longhorn
  destination:
    server: {{ .Values.cluster.server }}
    namespace: wg-easy
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
